# Generated by Django 4.0.4 on 2022-05-21 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ehPrincipal', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SubDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=70)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoper_scraping.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=200)),
                ('stock_qty', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('subdepartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoper_scraping.subdepartamento')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdate', models.DateTimeField()),
                ('price', models.FloatField()),
                ('savingPercentage', models.CharField(max_length=4, null=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoper_scraping.loja')),
            ],
        ),
        migrations.CreateModel(
            name='LinkOfertaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoper_scraping.oferta')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoper_scraping.produto')),
            ],
        ),
    ]
