# Generated by Django 4.0.4 on 2022-05-21 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoper_scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='produto',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='shoper_scraping.produto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LinkOfertaProduto',
        ),
    ]
