# Generated by Django 4.0.4 on 2022-05-21 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoper_scraping', '0002_oferta_produto_delete_linkofertaproduto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='lastUpdate',
        ),
        migrations.AddField(
            model_name='oferta',
            name='data_captura',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 14, 55, 15, 604030)),
        ),
    ]
