# Generated by Django 4.0.4 on 2022-05-23 03:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoper_scraping', '0005_alter_oferta_data_captura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='data_captura',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 3, 26, 7, 442525, tzinfo=utc)),
        ),
    ]
